

export default `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi nec ligula sed nulla rutrum lobortis. Sed ac risus massa. Vivamus feugiat urna quis nibh tincidunt fringilla. Pellentesque sapien leo, viverra vitae lacinia nec, pretium eget libero. Proin a eleifend arcu, eu dapibus lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vestibulum diam ut ipsum posuere aliquet. Nam consequat tempus tellus, eu pretium turpis. Suspendisse pharetra ante ut augue vulputate euismod. Vivamus dolor augue, mattis et tempor sit amet, ornare a erat. Vivamus porttitor rhoncus tincidunt. Nam ut felis eget sapien feugiat egestas id a mauris. Etiam sed mauris dignissim, fringilla orci a, auctor tellus. Quisque maximus ante ipsum. Nam sollicitudin efficitur dolor. In ut fringilla elit, non scelerisque nulla.

Sed euismod quam eget lorem feugiat, tristique euismod massa fermentum. In hac habitasse platea dictumst. Ut nec urna vel neque ultricies convallis vel eget nunc. Etiam nec ex tincidunt, iaculis lacus nec, egestas massa. Cras venenatis mi id rhoncus dictum. Nullam suscipit ut augue eget consectetur. Praesent suscipit gravida purus.

Vivamus iaculis diam nisl, et mattis sapien tempor non. Nulla vulputate ut justo a iaculis. Duis posuere sit amet ex non cursus. Sed a nisl tellus. Etiam id cursus nulla. Sed et nibh pharetra tortor tincidunt faucibus. Integer magna enim, lacinia sit amet vulputate a, pellentesque a libero.

Proin elementum, sem eu ultrices aliquam, leo dui volutpat ante, hendrerit accumsan eros massa a elit. Praesent id ex tempor, tempor ligula vitae, pellentesque arcu. Donec elementum justo ac augue varius vulputate. Praesent ultricies consectetur augue vitae accumsan. Mauris finibus eros dictum neque semper, a fringilla magna laoreet. Nunc auctor est eu lobortis varius. Praesent pulvinar ligula nec ligula mollis, nec tincidunt erat tempus. Cras laoreet purus sed lacus tincidunt convallis. Interdum et malesuada fames ac ante ipsum primis in faucibus.

In hendrerit semper velit, id convallis mi gravida id. Nulla imperdiet nibh convallis mauris scelerisque mollis. Sed facilisis, urna vel pretium pharetra, erat massa dignissim velit, commodo volutpat est nisi sit amet lectus. Donec mattis aliquet enim vel consequat. Nulla in ipsum quis justo accumsan fermentum. Cras a nisi et ante lacinia ornare vitae eget nunc. Proin eleifend, felis at euismod pellentesque, neque dolor molestie augue, nec auctor tellus odio ac lectus. Suspendisse vitae lectus neque. Pellentesque sit amet pulvinar est. `